# This is a generated file. Not intended for manual editing.
services:
  uvs.presentation:
    build:
      context: "/home/ashry/RiderProjects/UVS"
      dockerfile: "UVS.Presentation/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57402"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "uvs.presentation:dev"
    ports:
    - "127.0.0.1:57002:57000"
    - "127.0.0.1:57202:57200"
    - "127.0.0.1:57402:57402"
    volumes:
    - "/home/ashry/RiderProjects/UVS/UVS.Presentation:/app:rw"
    - "/home/ashry/RiderProjects/UVS:/src:rw"
    - "/home/ashry/.nuget/packages:/home/app/.nuget/packages"
    - "/home/ashry/.local/share/JetBrains/RiderRemoteDebugger/2025.1.3/Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "/home/ashry/.local/share/JetBrains/Toolbox/apps/rider/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/home/ashry/.cache/JetBrains/Rider2025.1/log/DebuggerWorker/JetBrains.Debugger.Worker.2025_7_02_21_14_53:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
